// src/app/component/trabajadores-lista/trabajadores-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';
import { TrabajadoresService } from '../../service/trabajadores.service';
import { RouterModule } from '@angular/router';

export interface Trabajador {
  idTrabajador: number;
  nombreCompleto: string;
  tipoDocumento: string;
  numeroDocumento: string;
  cargo: string;
  sueldo: number;
  moneda: string;
  estadoContrato: string;
}

@Component({
  selector: 'app-trabajadores-lista',
  standalone: true,
  imports: [CommonModule, RouterModule, HttpClientModule],
  templateUrl: './trabajadores-lista.component.html',
  styleUrls: ['./trabajadores-lista.component.css'],
  providers: [TrabajadoresService]
})
export class TrabajadoresListaComponent implements OnInit {
  trabajadores: Trabajador[] = [];
  loading = true;
  error = '';

  constructor(private trabajadoresService: TrabajadoresService) {}

  ngOnInit(): void {
    this.trabajadoresService.getTrabajadores().subscribe({
      next: (data: Trabajador[]) => {
        this.trabajadores = data;
        this.loading = false;
      },
      error: (err: any) => {
        this.error = 'Error al cargar trabajadores';
        this.loading = false;
      }
    });
  }
}
<div class="trabajadores-container">
  <h2 class="titulo-lista"><b>Lista de Trabajadores</b></h2>
  <div class="card-lista">
    <div class="header-lista">
      <input class="input-buscar" placeholder="Buscar por nombre, DNI, etc." />
      <button class="btn-buscar">Buscar</button>
    </div>
    <table class="tabla-trabajadores">
      <thead>
      <tr>
      <th>Nombre</th>
      <th>Tipo de Doc.</th>
      <th>Numero de Doc.</th>
      <th>Cargo</th>
      <th>Sueldo</th>
      <th>Moneda</th>
      <th>Estado del contrato</th>
      <th>Más info</th>
      </tr>
      </thead>
      <tbody>
      <tr *ngFor="let emp of trabajadores">
      <td>{{ emp.nombreCompleto }}</td>
      <td>{{ emp.tipoDocumento }}</td>
      <td><b>{{ emp.numeroDocumento }}</b></td>
      <td>{{ emp.cargo }}</td>
      <td>{{ emp.sueldo }}</td>
      <td>{{ emp.moneda }}</td>
      <td>{{ emp.estadoContrato }}</td>
      <td><button type="button" class="btn-info" [routerLink]="['/sistema/trabajadores', emp.idTrabajador]">Más info</button></td>
      </tr>
      </tbody>
    </table>
    <div class="footer-lista">
      <button class="btn-planilla">Generar planilla</button>
      <button type="button" class="btn-agregar" [routerLink]="['/sistema/trabajadores/nuevo']">+</button>
    </div>
  </div>
</div>
<div *ngIf="!loading && !error && pieChartOptions.series && pieChartOptions.series.length > 0">
  <apx-chart 
    [series]="pieChartOptions.series"
    [chart]="pieChartOptions.chart"
    [labels]="pieChartOptions.labels"
    [responsive]="pieChartOptions.responsive"
    [legend]="pieChartOptions.legend"
    [title]="pieChartOptions.title">
  </apx-chart>
</div>

// src/app/component/gestionar-trabajadores/TrabajadoresLista.jsx
import React, { useEffect, useState } from "react";
import axios from "axios";

const EmpleadosLista = () => {
  const [trabajadores, setTrabajadores] = useState([]);
  const [busqueda, setBusqueda] = useState("");

  useEffect(() => {
    axios.get("/api/empleados").then((res) => setTrabajadores(res.data));
  }, []);

  const trabajadoresFiltrados = trabajadores.filter((emp) =>
    (emp.nombreCompleto + emp.numeroDocumento)
      .toLowerCase()
      .includes(busqueda.toLowerCase())
  );

  return (
    <div className="empleados-lista-container">
      <h1 className="titulo">Lista de Empleados</h1>
      <div className="buscador">
        <input
          type="text"
          placeholder="Buscar por nombre, DNI, etc."
          value={busqueda}
          onChange={(e) => setBusqueda(e.target.value)}
        />
        <button>Buscar</button>
      </div>
      <table className="tabla-empleados">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Tipo de Doc.</th>
            <th>Numero de Doc.</th>
            <th>Cargo</th>
            <th>Sueldo</th>
            <th>Moneda</th>
            <th>Estado del contrato</th>
            <th>Más info</th>
          </tr>
        </thead>
        <tbody>
          {trabajadoresFiltrados.map((emp) => (
            <tr key={emp.idTrabajador}>
              <td>{emp.nombreCompleto}</td>
              <td>{emp.tipoDocumento}</td>
              <td style={{ fontWeight: "bold" }}>{emp.numeroDocumento}</td>
              <td>{emp.cargo}</td>
              <td>S/.{emp.sueldo}</td>
              <td>{emp.moneda}</td>
              <td>{emp.estadoContrato}</td>
              <td>
                <button className="info-btn">+ Info</button>
              </td>
            </tr>
          ))}
          {}
          {[...Array(5 - trabajadoresFiltrados.length)].map((_, i) => (
            <tr key={`empty-${i}`}>
              <td colSpan={8} style={{ background: "#f6fafd" }}>&nbsp;</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="acciones">
        <button className="planilla-btn">Generar planilla</button>
        <button className="agregar-btn">+</button>
      </div>
    </div>
  );
};

export default EmpleadosLista;
