// src/app/component/gestionar-empleados/EmpleadosLista.jsx
import React, { useEffect, useState } from "react";
import axios from "axios";

const EmpleadosLista = () => {
  const [empleados, setEmpleados] = useState([]);
  const [busqueda, setBusqueda] = useState("");

  useEffect(() => {
    axios.get("/api/empleados").then((res) => setEmpleados(res.data));
  }, []);

  const empleadosFiltrados = empleados.filter((emp) =>
    (emp.nombreCompleto + emp.numeroDocumento)
      .toLowerCase()
      .includes(busqueda.toLowerCase())
  );

  return (
    <div className="empleados-lista-container">
      <h1 className="titulo">Lista de Empleados</h1>
      <div className="buscador">
        <input
          type="text"
          placeholder="Buscar por nombre, DNI, etc."
          value={busqueda}
          onChange={(e) => setBusqueda(e.target.value)}
        />
        <button>Buscar</button>
      </div>
      <table className="tabla-empleados">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Tipo de Doc.</th>
            <th>Numero de Doc.</th>
            <th>Cargo</th>
            <th>Sueldo</th>
            <th>Moneda</th>
            <th>Estado del contrato</th>
            <th>Más info</th>
          </tr>
        </thead>
        <tbody>
          {empleadosFiltrados.map((emp) => (
            <tr key={emp.idTrabajador}>
              <td>{emp.nombreCompleto}</td>
              <td>{emp.tipoDocumento}</td>
              <td style={{ fontWeight: "bold" }}>{emp.numeroDocumento}</td>
              <td>{emp.cargo}</td>
              <td>S/.{emp.sueldo}</td>
              <td>{emp.moneda}</td>
              <td>{emp.estadoContrato}</td>
              <td>
                <button className="info-btn">+ Info</button>
              </td>
            </tr>
          ))}
          {/* Rellenar filas vacías para igualar el diseño */}
          {[...Array(5 - empleadosFiltrados.length)].map((_, i) => (
            <tr key={`empty-${i}`}>
              <td colSpan={8} style={{ background: "#f6fafd" }}>&nbsp;</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="acciones">
        <button className="planilla-btn">Generar planilla</button>
        <button className="agregar-btn">+</button>
      </div>
    </div>
  );
};

export default EmpleadosLista;

// src/app/component/empleados-lista/empleados-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClientModule } from '@angular/common/http'; // Importa esto
import { EmpleadosService } from '../../service/empleados.service';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-empleados-lista',
  standalone: true,
  imports: [CommonModule, RouterModule, HttpClientModule], // Agrega HttpClientModule aquí
  templateUrl: './empleados-lista.component.html',
  styleUrls: ['./empleados-lista.component.css'],
  providers: [EmpleadosService]
})
export class EmpleadosListaComponent implements OnInit {
  empleados: any[] = [];
  loading = true;
  error = '';

  constructor(private empleadosService: EmpleadosService) {}

  ngOnInit(): void {
    this.empleadosService.getEmpleados().subscribe({
      next: (data) => {
        this.empleados = data;
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Error al cargar empleados';
        this.loading = false;
      }
    });
  }
}
<div class="empleados-container">
  <h2 class="titulo-lista"><b>Lista de Empleados</b></h2>
  <div class="card-lista">
    <div class="header-lista">
      <input class="input-buscar" placeholder="Buscar por nombre, DNI, etc." />
      <button class="btn-buscar">Buscar</button>
    </div>
    <table class="tabla-empleados">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Tipo de Doc.</th>
          <th>Numero de Doc.</th>
          <th>Cargo</th>
          <th>Sueldo</th>
          <th>Moneda</th>
          <th>Estado del contrato</th>
          <th>Más info</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let emp of empleados">
            <td>{{ emp.nombreCompleto }}</td>
            <td>{{ emp.tipoDocumento }}</td>
            <td><b>{{ emp.numeroDocumento }}</b></td>
            <td>{{ emp.cargo }}</td>
            <td>{{ emp.sueldo }}</td>
            <td>{{ emp.moneda }}</td>
            <td>{{ emp.estadoContrato }}</td>
        </tr>
      </tbody>
    </table>
    <div class="footer-lista">
      <button class="btn-planilla">Generar planilla</button>
      <button class="btn-agregar">+</button>
    </div>
  </div>
</div>
